from __future__ import annotations

from typing import Any


def prepare_component_icon_pixels(tex_data: Any) -> tuple[list[int], int, int]: ...
def bump_component_structure_version() -> None: ...
def get_component_structure_version() -> int: ...
def ensure_material_file_path(material: Any) -> str: ...